import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navigation from '@/components/Navigation/Navigation'
import DashboardHeader from '@/components/shared/DashboardHeader'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="main-dashboard" className='h-screen w-screen flex'>
          <Navigation />
          <div id="dashboard-content" className='w-full h-full'>
            <DashboardHeader />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}

export default RootLayout;
